sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '6'
script:
  - yarn run lint
  - yarn run build
  - yarn run test -- --coverage
after_success:
  - yarn run report-coverage
  - yarn run release
branches:
  only:
    - master